app:
  build: .
  environment:
    INFLUXDB_HOST: 'influxdb'
    INFLUXDB_PORT: '8086'
    INFLUXDB_DATABASE: 'metrics_test'
    INFLUXDB_USER: 'root'
    INFLUXDB_PASSWORD: 'root'
  links:
   - influxdb
  volumes:
   - .:/var/www/app
  ports:
   - "3000:3000"
  command: bundle exec rails s -b 0.0.0.0 puma
influxdb:
  image: tutum/influxdb
  ports:
   - "8083:8083"
   - "8086:8086"
  environment:
    PRE_CREATE_DB: 'metrics_test'
grafana:
  image: grafana/grafana
  ports:
   - "3001:3000"
